/*
 * DO NOT EDIT THIS FILE, your changes will be overwritten
 * This is an automatically generated file.
 * It was generated with uasm, the microassembler, on
 * Sat Jul 23 12:02:04 2022
 */

/*
 * The assembly file generated a total data width of 44 bits for 
 * 9 fields. The maximum address encountered was 0x7ff, needing 
 * 11 bits
 */

module MICROCODE_ROM (ADDR_in,ROM_out);
   input  [10:0] ADDR_in;
   output [43:0] ROM_out;

   reg    [43:0] ROM_out_r;

   assign ROM_out = ROM_out_r;
   always @(ADDR_in)
     begin
        case(ADDR_in)
          /* START: */
          11'h0: ROM_out_r = 44'b000_000_001_0000_0000_0_0000_0000000000000000_100000;
          11'h1: ROM_out_r = 44'b000_000_010_0000_0000_0_0000_0000000000000001_100000;
          11'h2: ROM_out_r = 44'b000_000_100_0000_0000_0_0000_0000000000000010_100000;
          11'h3: ROM_out_r = 44'b001_010_011_0100_1111_0_0000_0000000000000000_000000;
          11'h4: ROM_out_r = 44'b000_000_000_0000_0000_0_0010_0000000000000110_000000;
          11'h5: ROM_out_r = 44'b100_001_100_0011_1111_0_0001_0000000000001001_000000;
          /* L1: */
          11'h6: ROM_out_r = 44'b000_000_000_0000_0000_0_0101_0000000000001000_000000;
          11'h7: ROM_out_r = 44'b100_000_100_0001_1100_0_0001_0000000000001001_000000;
          /* L2: */
          11'h8: ROM_out_r = 44'b100_010_100_0011_1111_0_0000_0000000000000000_000000;
          /* DONE: */
          11'h9: ROM_out_r = 44'b100_000_000_0000_0000_0_0001_0000000000000000_000000;
          11'h7ff: ROM_out_r = 44'b000_000_000_0000_0000_0_0000_0000000000000000_000000;
          default: ROM_out_r = 44'b0;
       endcase
     end
endmodule
