--
-- DO NOT EDIT THIS FILE, your changes will be overwritten
-- This is an automatically generated file.
-- It was generated with uasm, the microassembler, on
-- Sat Jul 23 13:55:03 2022
--
--
--
-- Yeilding a total data width of 44 bits for 9 fields.
-- The maximum address encountered was 0x7ff, needing 11 bits
--
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

entity MICROCODE_ROM is
port( ADDR_IN  : in  unsigned(10 downto 0);
      DATA_OUT : out std_logic_vector(43 downto 0));
end MICROCODE_ROM;

architecture RTL of MICROCODE_ROM is

   signal DATA_OUT_R : std_logic_vector(43 downto 0);
begin
   DATA_OUT <= DATA_OUT_R;

   process(ADDR_IN)
     begin
        case ADDR_IN is
          -- START:
          when "00000000000" => DATA_OUT_R <= "00000000100000000000000000000011111110100000";
          when "00000000001" => DATA_OUT_R <= "00000001000000000000000000000000000000100000";
          when "00000000010" => DATA_OUT_R <= "00000001100000000000000000000000000000100000";
          when "00000000011" => DATA_OUT_R <= "00000010100000000000000000000000010000100000";
          when "00000000100" => DATA_OUT_R <= "00000011000000000000000000000000000000100000";
          -- CHECK_NEXT_BIT:
          when "00000000101" => DATA_OUT_R <= "10101100001001000001000000000000001001000000";
          when "00000000110" => DATA_OUT_R <= "01100001100010000000000000000000000000000000";
          -- CHECK_MSB:
          when "00000000111" => DATA_OUT_R <= "00100000111010010000110000000000000101000000";
          -- INCREMENT_BITCOUNT:
          when "00000001000" => DATA_OUT_R <= "01000001000010000000010000000000000101000000";
          -- DONE:
          when "00000001001" => DATA_OUT_R <= "00000011000000000000000000000000000001100000";
          when "00000001010" => DATA_OUT_R <= "00000000000000000000010000000000000000000000";
          when "11111111111" => DATA_OUT_R <= "00000000000000000000000000000000000000000000";
          when others => DATA_OUT_R <= "00000000000000000000000000000000000000000000";
       end case;
     end process;
end RTL;
